version: '3'
services:
  backend:
    build: ./Server
    ports:
      - '5000:5000'
    networks:
      - chatnet

  frontend:
    build: ./client
    ports:
      - '3000:80'
    networks:
      - chatnet

networks:
  chatnet:
